SafeBusiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from viewer.views import home, statistics_view, companies, about_us, company_detail, search, \
    top_10_yoy_sales_view, top_10_tax_debt_view, top_10_social_insurance_debt_view, top_10_health_insurance_debt_view, \
    top_10_employee_count_view, ExecutiveFormView, privacy_policy, terms_of_service, CompanyCreateView, \
    CompanyUpdateView, CompanyDeleteView
from accounts.views import SubmittableLoginView, SubmittablePasswordChangeView, SignUpView, subscribe

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('database/', companies, name='database'),
    path('statistics/', statistics_view, name='statistics'),
    path('about_us/', about_us, name='about_us'),
    path('company/create/', CompanyCreateView.as_view(), name='company_create'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    path('company/delete/<int:pk>/', CompanyDeleteView.as_view(), name='company_delete'),
    path('company/<int:company_id>/', company_detail, name='company_detail'),
    path('subscribe/', subscribe, name='subscribe'),  # Pridajte lomku na koniec
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    path('terms-of-service/', terms_of_service, name='terms_of_service'),
    path('executive/create/', ExecutiveFormView.as_view(), name='executive_create'),

    # Authentication
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Search and Top 10 Views
    path('search/', search, name='search'),
    path('top-10-yoy-sales/', top_10_yoy_sales_view, name='top_10_yoy_sales'),
    path('top-10-tax-debt/', top_10_tax_debt_view, name='top_10_tax_debt'),
    path('top-10-social-insurance-debt/', top_10_social_insurance_debt_view, name='top_10_social_insurance_debt'),
    path('top-10-health-insurance-debt/', top_10_health_insurance_debt_view, name='top_10_health_insurance_debt'),
    path('top-10-employee-count/', top_10_employee_count_view, name='top_10_employee_count'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    personal_id_number = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"Profile of {self.user.username}"

accounts/views.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.db.transaction import atomic
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from accounts.models import Profile
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse


def home(request):
    return render(request, 'home.html')


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(
        required=False,
        input_formats=['%d/%m/%Y'],  # Formát, ktorý očakávame pri vstupe
        widget=forms.DateInput(attrs={'type': 'text', 'placeholder': 'DD/MM/YYYY'})
    )
    employee_id_number = forms.CharField(label='Employee ID Number', max_length=50, required=False)
    personal_number = forms.CharField(label='Personal Number', max_length=50, required=False)
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    @atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            Profile.objects.create(
                user=user,
                birth_date=self.cleaned_data['birth_date'],
                employee_id_number=self.cleaned_data['employee_id_number'],
                personal_number=self.cleaned_data['personal_number']
            )
        return user


class SubmittableLoginView(LoginView):
    template_name = 'form.html'


class SubmittablePasswordChangeView(PasswordChangeView):
    template_name = 'form.html'
    success_url = reverse_lazy('home')


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, 'Registration successful.')
        return redirect(self.success_url)

    def form_invalid(self, form):
        messages.error(self.request, 'There was a problem with your registration.')
        return self.render_to_response(self.get_context_data(form=form))


def subscribe(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        # Tu pridajte kód na spracovanie emailu (napr. uloženie do databázy)
        return HttpResponse("Thank you for subscribing!")
    return redirect('/')  # Alebo vráťte späť na hlavnú stránku

accounts/templates/form.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-container">
                <h2>{{ form_title }}</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    <input type="submit" value="Submit" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}
{% block form_title %}Sign up{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-container">
                <h2>Sign up</h2>
                <form method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="id_username" class="form-label">Username:</label>
                        {{ form.username }}
                        <small class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
                    </div>

                    <div class="form-group">
                        <label for="id_password1" class="form-label">Password:</label>
                        {{ form.password1 }}
                        <small class="form-text text-muted">Your password can’t be too similar to your other personal information. Your password must contain at least 8 characters. Your password can’t be a commonly used password. Your password can’t be entirely numeric.</small>
                    </div>

                    <div class="form-group">
                        <label for="id_password2" class="form-label">Password confirmation:</label>
                        {{ form.password2 }}
                        <small class="form-text text-muted">Enter the same password as before, for verification.</small>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="form-label">Email:</label>
                        {{ form.email }}
                        <small class="form-text text-muted">Please enter a valid email address.</small>
                    </div>

                    <div class="form-group">
                        <label for="id_personal_number" class="form-label">Personal ID Number:</label>
                        {{ form.personal_number }}
                        <small class="form-text text-muted">Please enter your personal ID number.</small>
                    </div>

                    <div class="form-group">
                        <label for="id_birth_date" class="form-label">Birth Date:</label>
                        {{ form.birth_date }}
                        <small class="form-text text-muted">Please enter your birth date in DD/MM/YYYY format.</small>
                    </div>

                    <input type="submit" value="Sign up" class="btn btn-primary">
                </form>

                {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field, errors in form.errors.items %}
                        <li>{{ field }}: {{ errors }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}