SafeBusiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from viewer.views import home, statistics_view, companies, about_us, company_detail, search, \
    top_10_yoy_sales_view, top_10_tax_debt_view, top_10_social_insurance_debt_view, top_10_health_insurance_debt_view, \
    top_10_employee_count_view, ExecutiveFormView, privacy_policy, terms_of_service, CompanyCreateView, \
    CompanyUpdateView, CompanyDeleteView
from accounts.views import SubmittableLoginView, SubmittablePasswordChangeView, SignUpView, subscribe

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('database/', companies, name='database'),
    path('statistics/', statistics_view, name='statistics'),
    path('about_us/', about_us, name='about_us'),
    path('company/create/', CompanyCreateView.as_view(), name='company_create'),
    path('company/update/<int:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    path('company/delete/<int:pk>/', CompanyDeleteView.as_view(), name='company_delete'),
    path('company/<int:company_id>/', company_detail, name='company_detail'),
    path('subscribe/', subscribe, name='subscribe'),  # Pridajte lomku na koniec
    path('privacy-policy/', privacy_policy, name='privacy_policy'),
    path('terms-of-service/', terms_of_service, name='terms_of_service'),
    path('executive/create/', ExecutiveFormView.as_view(), name='executive_create'),

    # Authentication
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Search and Top 10 Views
    path('search/', search, name='search'),
    path('top-10-yoy-sales/', top_10_yoy_sales_view, name='top_10_yoy_sales'),
    path('top-10-tax-debt/', top_10_tax_debt_view, name='top_10_tax_debt'),
    path('top-10-social-insurance-debt/', top_10_social_insurance_debt_view, name='top_10_social_insurance_debt'),
    path('top-10-health-insurance-debt/', top_10_health_insurance_debt_view, name='top_10_health_insurance_debt'),
    path('top-10-employee-count/', top_10_employee_count_view, name='top_10_employee_count'),
]

viewer/models.py
from django.db import models


class Executive(models.Model):
    executive_name = models.CharField(max_length=255, blank=False)
    executive_address = models.CharField(max_length=255, blank=False)
    executive_city = models.CharField(max_length=255, blank=False)

    def __str__(self):
        return self.executive_name


class Company(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_name = models.CharField(max_length=255, blank=False)
    year_of_foundation = models.IntegerField(blank=False, default=0)
    executives = models.ManyToManyField(Executive, related_name='companies')
    executive_year_of_change = models.IntegerField(blank=False, default=0)
    executive_change_count = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return self.company_name


class RegisteredOffice(models.Model):
    registered_office_address = models.CharField(max_length=255, blank=False)
    registered_office_city = models.CharField(max_length=255, blank=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='registered_offices', to_field='company_id')

    def __str__(self):
        return f"{self.registered_office_address}, {self.registered_office_city}"


class Employee(models.Model):
    employee_count = models.IntegerField(blank=False)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='employees', to_field='company_id')

    def __str__(self):
        return f"{self.employee_count} employees at {self.company}"


class Revenue(models.Model):
    revenue_year = models.IntegerField(blank=False)
    YoY_increase_in_sales = models.IntegerField(blank=False)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='revenue', to_field='company_id')

    def __str__(self):
        return f"{self.YoY_increase_in_sales} in {self.revenue_year}"


class CompanyDebt(models.Model):
    tax_office_debt = models.IntegerField(blank=False)
    social_insurance_agency_debt = models.IntegerField(blank=False)
    health_insurance_company_debt = models.IntegerField(blank=False)
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='company_debts', to_field='company_id')

    def __str__(self):
        return f"Debt for {self.company}"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="sk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SafeBusiness{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <header class="header">
        <!-- Štýly pre header -->
    </header>

    {% include 'nav.html' %}  <!-- Načítanie navigačného baru -->

    <main>
        {% block content %}
        <!-- Obsah šablóny bude vložený sem -->
        {% endblock %}
    </main>

    {% include 'footer.html' %}  <!-- Načítanie footer baru -->

    <!-- jQuery, Popper.js a Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer-content">
            <div class="contact-info">
                <p>Email: <a href="mailto:info@safebusiness.com">info@safebusiness.com</a></p>
            </div>

            <div class="legal">
                <a href="/privacy-policy">Privacy Policy</a>
                <a href="/terms-of-service">Terms of Service</a>
            </div>

            <div class="newsletter-signup">
                <p>Newsletter subscribe:</p>
                    <form action="{% url 'subscribe' %}" method="post">
                        {% csrf_token %}
                        <input type="email" name="email" placeholder="Your email address" required>
                    </form>
            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <p>&copy; 2024 SafeBusiness s.r.o. All rights reserved. Designed by M&R s.r.o.</p>
    </div>
</footer>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- Logo namiesto názvu -->
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'images/safe_business_logo1.png' %}" alt="SafeBusiness Logo" class="logo-nav">
        </a>
        <!-- Toggler pre mobilné zobrazenie -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Obsah navigačného panela -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'database' %}">Database</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'statistics' %}">Statistics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about_us' %}">About us</a>
                </li>
                {% if user.is_authenticated %}
                    {% if perms.viewer.add_company %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company_create' %}">Add Company</a>
                        </li>
                    {% endif %}
                    {% if perms.viewer.add_executive %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'executive_create' %}">Add Executive</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if user.first_name %}Hello, {{ user.first_name }}!
                            {% else %}Hello, {{ user.username }}!{% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="guestDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            You are not logged in.
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="guestDropdown">
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'signup' %}">Sign-up</a>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>